branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
before_install: 
  - sudo apt-get install libgd-gd2-perl libpng libgd2-xpm-dev libgd-graph-perl
script: "perl Makefile.PL && make disttest"
