branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
before_install: 
  - sudo apt-get install libgd2-xpm-dev 
script: "perl Makefile.PL && make disttest"
