branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
before_install: 
  - sudo apt-cache search libgd | grep perl
  - sudo apt-get install libgd-gd2-perl
script: "perl Makefile.PL && make disttest"
