name: Run tests latest version of perl
jobs:
  check:
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - run: cpanm --installdeps .
      - run: prove -lv t
