name: Run tests latest version of perl
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
      - run: cpanm --installdeps .
      - name: Run tests
        run: prove -lv t
